### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by szhang963** [tobiasfshr/map4d#1]
Hi, I am interested in your impressive work.

Could you let me know when you will release the code?

Best.

**Comment by tobiasfshr** [comment]
Hey, for ML-NSG we are going to release the code in the next 2 weeks, for 4DGF we are waiting for legal approval, so might take a bit longer but we’ll do our best to release it ASAP!

**Comment by GopiRajuMatta** [comment]
Any update on code release of ML-NSG and 4DGF?

**Comment by tobiasfshr** [comment]
Closing as code is released
