### ISSUE TITLE
Visualize by ns-viewer but the results are not good

### ISSUE THREAD

**Issue by RyanPham19092002** [tobiasfshr/map4d#10]
Hi! Thanks for your great work.
When I tried to visualize by ns-viewer, the result is blur and not well like the image below
![image](https://github.com/user-attachments/assets/f8518e37-0eae-4375-bb01-93282c56d4f6)

How can I fix that ? Thanks for your help.

**Comment by tobiasfshr** [comment]
Hi, please try to increase the max res parameter in the viewer, this should give more high quality views.

**Comment by RyanPham19092002** [comment]
I tried to increase resolution and it's work. Thanks for your help
