### ISSUE TITLE
KITTI dataset

### ISSUE THREAD

**Issue by HHollowAU** [tobiasfshr/map4d#14]
you have a good job,but i have some base problem.the training file is this?
<img width="184" alt="1731077093026" src="https://github.com/user-attachments/assets/7fde2d7c-6609-4c28-8b60-1954a4a446ac">
and the calib file is uncommon to the error,how should i orgnize the kitti dataset?
<img width="155" alt="1731077449479" src="https://github.com/user-attachments/assets/2d9aa2ec-e682-4b8e-a889-250665822977">
<img width="618" alt="1731077467267" src="https://github.com/user-attachments/assets/ea07f051-4042-434a-9bc3-c41b28e97ff8">

**Comment by tobiasfshr** [comment]
Hi, are you sure you have the right data split? All data (calib, images, etc) should be provided here: https://www.cvlibs.net/datasets/kitti/eval_tracking.php

**Comment by HHollowAU** [comment]
I find the method to download kitti dataset from this.
<img width="480" alt="1731149309032" src="https://github.com/user-attachments/assets/a7103cc8-24a1-4b5c-bc9e-a87b1c6ca2cd">
should i download these?thanks!
<img width="292" alt="1731152933058" src="https://github.com/user-attachments/assets/e82a6f30-3718-4dac-acd6-739a6ecf21e6">
