### ISSUE TITLE
RuntimeError: Encoding 'SequentialGrid' not found

### ISSUE THREAD

**Issue by HHollowAU** [tobiasfshr/map4d#15]
I particularly appreciate your research.
When I run ns-train 4dgf-kitti street --data data/KITTI/tracking/training/metadata_0002.pkl --train-split-fraction 0.75,
I meet a problem.
<img width="749" alt="1731294472854" src="https://github.com/user-attachments/assets/dddd7f14-0472-4e37-bc8e-ac5543a3a5dd">
Is the version of tinycudann not suit?
I install tinycudann by pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch.

**Comment by tobiasfshr** [comment]
Please make sure to closely follow the instructions in the README. We install a modified version of tinycudann:
```pip install ninja git+https://github.com/hturki/tiny-cuda-nn.git@ht/res-grid#subdirectory=bindings/torch```

**Comment by HHollowAU** [comment]
Thanks!
I use the command ns-train 4dgf-kitti street --data data/KITTI/tracking/training/metadata_0002.pkl --train-split-fraction 0.75,meet terminated, is cuda outof memory?
<img width="723" alt="1731387193701" src="https://github.com/user-attachments/assets/568e8a7f-a0cc-4c01-bea3-fafb1bb26f63">
The command is different from ns-train 4dgf-kitti --data /home/zx/map4d/data/KITTI/tracking/training/metadata_0002.pkl?

**Comment by tobiasfshr** [comment]
seems like your system terminated the process. You may not have enough RAM? CUDA out of memory would usually print a more informative error message.

**Comment by HHollowAU** [comment]
Thanks！
