### ISSUE TITLE
Training is very slow

### ISSUE THREAD

**Issue by qian5683** [tobiasfshr/map4d#17]
I tried to train Dynamic 3D Gaussian Fields on the Argovese2 dataset using 3 V100 GPU, but the training process was very slow. How long did it take for you to train

**Comment by tobiasfshr** [comment]
We train approx. 2.5 days across 8 A100 GPUs. Note that the Argoverse data splits consist of 10K+ images, so it needs to train much longer than smaller-scale scenes
