### ISSUE TITLE
Novel View Synthesis

### ISSUE THREAD

**Issue by Himanshunitrr** [tobiasfshr/map4d#6]
This might be a stupid question but wanted to know given few videos of a common underlying landmark, how can I get the view directly? Is it this [Rendering section](https://github.com/tobiasfshr/map4d?tab=readme-ov-file#rendering)?

**Comment by jkulhanek** [comment]
Hi, thanks for the question. Can you please clarify what you mean? Do you want to use the videos for reconstruction? In that case, you need to obtain camera poses, etc. first before you can train the model. Or is the question more about how to perform rendering given a trained model? This is described in the Rendering section.
